name: Coverage Check on PR
on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      COV_MIN: 0
    container:
      image: node:22

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm run cover:report

      - name: Run coverage extraction script
        id: extract_coverage
        run: |
          # Capture the output of the console log from the Node script
          COVERAGE=$(node -e "
            const { extractCoverage } = require('@nicolawealth/code_coverage_extractor');
            const result = extractCoverage('./coverage/coverage-final.json', './codecov/badge.json');
            console.log(result);
          " | xargs)
      
          # Set the captured coverage value as a GitHub environment variable
          echo "COVERAGE=$COVERAGE" >> $GITHUB_ENV
      
      - name: Confirm Coverage Value
        run: |
          # Check if the coverage value is 100% and fail if it's not
          if [ "$COVERAGE" -ne 100 ]; then
            echo "Assertion failed: Coverage is not 100% (Actual: $COVERAGE%)"
            exit 1
          else
            echo "Assertion passed: Coverage is 100%"
          fi
