name: Coverage Check on PR
on:
  pull_request:
    branches:
      - main

jobs:
  coverage:
    runs-on: ubuntu-latest
    env:
      COV_MIN: 0
    container:
      image: node:22

    steps:
      - uses: actions/checkout@v3
        with:
          node-version: 22
      - run: npm ci
      - run: npm run cover:report

      - name: Log version of @nicolawealth/code_coverage_extractor
        run: |
          node -e "
          const path = require('path');
          const packageJson = require(path.resolve('./node_modules/@nicolawealth/code_coverage_extractor/package.json'));
          console.log('Using @nicolawealth/code_coverage_extractor version:', packageJson.version);
          "

      - name: Run coverage extraction script
        id: extract_coverage
        run: |
          node -e "
          const { extractCoverage } = require('@nicolawealth/code_coverage_extractor');
          const result = extractCoverage('./coverage/coverage-final.json', './codecov/badge.json');
          console.log('Extracted Coverage:', result);
          "
      
      - name: Confirm Coverage Value
        run: |
          # Check if the coverage value is 100% and fail if it's not
          if [ "$COVERAGE" -ne 100 ]; then
            echo "Assertion failed: Coverage is not 100% (Actual: $COVERAGE%)"
            exit 1
          else
            echo "Assertion passed: Coverage is 100%"
          fi
